name: projeto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # VersÃ£o recomendada para compatibilidade
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true